version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
    steps:
      # default shell is Powershell
      - checkout
      - run:
          command: echo hello && echo world
          shell: bash.exe
      - run:
          command: echo hello & echo world
          shell: cmd.exe
      - run:
          command: netsh interface ipv4 show excludedportrange protocol=tcp
          shell: cmd.exe
      - run:
          name: Get go version
          command: go version
      - run:
          name: Unit tests
          command: go test -v ./...